# -*- coding: utf-8 -*-
"""Week_4_Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILfbuQuFpIswscgBcGO6aEXnsALJnp7t
"""

import pandas as pd
import numpy as np

df = pd.read_csv("play_tennis.csv")

print(df.head())

import math

count_yes = (df['play'] == 'Yes').sum()
print(count_yes)

count_no = (df['play'] == "No").sum()

total_count = count_yes + count_no
p_yes = count_yes/total_count
p_no = count_no/total_count
full_entropy = -p_yes*math.log2(p_yes) - p_no*math.log2(p_no)

attribute_gains = {}

for y in df.columns[1:-1]:
  unique = df[y].unique()
  entropy = []
  weights = []
  for i in unique:
    df_attribute = df[df[y] == i]
    count_yes = (df_attribute['play'] == 'Yes').sum()
    count_no = (df_attribute['play'] == 'No').sum()
    tot = count_yes + count_no
    p_yes = count_yes/tot
    p_no = count_no/tot
    if(p_yes == 0 or p_no == 0):
      attribute_entropy = 1
    else :
      attribute_entropy = -p_yes*math.log2(p_yes) - p_no*math.log2(p_no)
    entropy.append(attribute_entropy)
    weight = (df[y] == i).sum()
    weights.append(weight/total_count)
    gain = full_entropy - np.sum(np.array(entropy)*np.array(weights))
    attribute_gains[y] = gain

print(attribute_gains)

max_attribute = "placeholder"
max_val = 0
for i in attribute_gains:
  if(attribute_gains[i] > max_val):
    max_val = attribute_gains[i]
    max_attribute = i

root = max_attribute

def calculate_entropy(df):
    target_column = 'play'
    count_yes = (df[target_column] == 'Yes').sum()
    count_no = (df[target_column] == 'No').sum()
    total_count = count_yes + count_no

    if total_count == 0:
        return 0.0

    p_yes = count_yes / total_count
    p_no = count_no / total_count

    entropy = 0.0
    if p_yes > 0:
        entropy -= p_yes * math.log2(p_yes)
    if p_no > 0:
        entropy -= p_no * math.log2(p_no)
    return entropy

def build_tree(df):
    target_column = 'play'

    if len(df[target_column].unique()) == 1:
        return df[target_column].iloc[0]

    features = [col for col in df.columns if col not in ['day', target_column]]
    if not features:
        return df[target_column].mode()[0]

    full_entropy = calculate_entropy(df)
    attribute_gains = {}

    for attribute in features:
        unique_values = df[attribute].unique()
        weighted_average_entropy = 0.0
        for value in unique_values:
            subset = df[df[attribute] == value]
            subset_entropy = calculate_entropy(subset)
            weight = len(subset) / len(df)
            weighted_average_entropy += weight * subset_entropy

        gain = full_entropy - weighted_average_entropy
        attribute_gains[attribute] = gain

    best_attribute = max(attribute_gains, key=attribute_gains.get)

    tree = {best_attribute: {}}

    for value in df[best_attribute].unique():
        subset = df[df[best_attribute] == value].copy()
        subset_for_recursion = subset.drop(columns=[best_attribute])
        tree[best_attribute][value] = build_tree(subset_for_recursion)

    return tree

decision_tree = build_tree(df)
print(decision_tree)

def print_tree(tree, indent=" "):
    for key, value in tree.items():
        if isinstance(value, dict):
            print(indent + str(key) + ":")
            print_tree(value, indent + "  ")
        else:
            print(indent + str(key) + ": " + str(value))

print("Decision Tree:")
print_tree(decision_tree)

print(root)

branches = df[root].unique()

print(branches)

for i in branches:
  df_branch = df[df[root] == i]
  df_branch.drop(root, axis = 1, inplace = True)

