# -*- coding: utf-8 -*-
"""Week_2_linear_regression_from_scratch.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhhbCpQhfVcNkmAi1PRMw0_E0mu2oGTH
"""

import random
import numpy as np
import matplotlib.pyplot as plt

years_of_experience = []
package = []
for i in range(100):
  years_of_experience.append(random.randint(1 , 25))
for i in range(100):
  package.append(max(2*years_of_experience[i] + random.randint(-10, 10) , 5))

years_of_experience = np.array(years_of_experience)
package = np.array(package)

print(years_of_experience)
print(package)

plt.scatter(years_of_experience , package)
plt.show()

def linear_regression(years_of_experience , package):
  x_avg = np.mean(years_of_experience)
  y_avg = np.mean(package)

  sum_num = 0
  sum_denom = 0
  for i in range(100):
    sum_num+=(years_of_experience[i]-x_avg)*(package[i]-y_avg)
    sum_denom+=(years_of_experience[i]-x_avg)*(years_of_experience[i]-x_avg)

  m = sum_num/sum_denom
  b = y_avg - m*x_avg

  return [m , b]

m , b = linear_regression(years_of_experience = years_of_experience , package = package)

y_pred = []
for i in years_of_experience:
  y_pred.append(i*m + b)

y_pred = np.array(y_pred)

plt.plot(years_of_experience , y_pred)
plt.scatter(years_of_experience , package)
plt.xlabel("Years of experience")
plt.ylabel("Package")
plt.show()