# -*- coding: utf-8 -*-
"""Week_3_Gradient_Descent_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BB0qmSmLHxC76-T_hRYR3drrXKeTtyts
"""

import random
import numpy as np
import matplotlib.pyplot as plt

years_of_experience = []
package = []
for i in range(100):
  years_of_experience.append(random.randint(1 , 25))
for i in range(100):
  package.append(max(2*years_of_experience[i] + random.randint(-10, 10) , 5))

years_of_experience = np.array(years_of_experience)
package = np.array(package)

print(years_of_experience)
print(package)

plt.scatter(years_of_experience , package)
plt.show()

def gradient_descent_linear_regression(years_of_experience, package):
    n = len(years_of_experience)
    m = random.randint(1, 10)
    b = random.randint(1, 10)

    loss_function = sum((m * years_of_experience[i] + b - package[i]) ** 2 for i in range(n))

    learning_rate = 0.0001
    max_iterations = 10000

    for iteration in range(max_iterations):
        slope_gradient = 0
        intercept_gradient = 0

        for i in range(n):
            slope_gradient += years_of_experience[i] * (package[i] - m * years_of_experience[i] - b)
            intercept_gradient += (package[i] - (m * years_of_experience[i] + b))

        slope_gradient *= (-2 / n)
        intercept_gradient *= (-2 / n)

        m = m - learning_rate * slope_gradient
        b = b - learning_rate * intercept_gradient

        new_loss_function = sum((m * years_of_experience[i] + b - package[i]) ** 2 for i in range(n))

        if abs(new_loss_function - loss_function) < 1e-6:
            break

        loss_function = new_loss_function

    return [m, b]

m , b = gradient_descent_linear_regression(years_of_experience = years_of_experience , package = package)

y_pred = []
for i in years_of_experience:
  y_pred.append(i*m + b)

y_pred = np.array(y_pred)

plt.plot(years_of_experience , y_pred)
plt.scatter(years_of_experience , package)
plt.xlabel("Years of experience")
plt.ylabel("Package")
plt.show()