# -*- coding: utf-8 -*-
"""Week_6_Logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WWQwlR0FCGergahqopW8Mn7meP_OokT
"""

import numpy as np

X = np.array([1, 2, 3, 4, 5, 6])
y = np.array([0, 0, 0, 1, 1, 1])

w = 0.0
b = 0.0
learning_rate = 0.01
epochs = 5000

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

n = len(X)

for epoch in range(epochs):

    z = w * X + b
    y_pred = sigmoid(z)

    dw = (1 / n) * np.sum((y_pred - y) * X)
    db = (1 / n) * np.sum(y_pred - y)

    w -= learning_rate * dw
    b -= learning_rate * db

def predict(x):
    prob = sigmoid(w * x + b)
    return 1 if prob >= 0.5 else 0

print("Weight:", w)
print("Bias:", b)

for x in X:
    print(f"X = {x}, Prediction = {predict(x)}")